### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by hongbo-miao** [dpim/rxjs-microsoft-graph#1]
Good start.
However, please don't move under microsoft-graph for now, the code still needs update to make it reusable.

**Comment by dpim** [comment]
Hongbo, I appreciate your feedback. I wasn’t planning on moving it under the Microsoft Graph organization. If you have suggestions on how to refactor the code, that would be great.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
